spring:
  application:
    name :authorization
  r2dbc:
    #url: r2dbc:mysql://localhost:3306/practice?zeroDateTimeBehavior=convertToNull&useSSL=false&useServerPrepareStatement=true
    #username: root
    #password: root
    logging:
      level: DEBUG
  sql:
    init:
      platform: mysql
    show-sql: true
    format-sql: true
server:
  port: 8091